# Sklearn Basics

## Linear Regression

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

housing = fetch_california_housing(as_frame=True)

df = housing.frame
df.head(5)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

## Model Train Split

In [ ]:
X = df.drop(colums=['MedHouseVal'])
y = df['MedHouseVal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MAE: ",mae)
print("MSE: ",mse)
print("RMSE: ", np.sqrt(mse))
print("R2: ",r2)

TypeError: DataFrame.drop() got an unexpected keyword argument 'colums'. Did you mean 'columns'?

## Hours Studied

In [ ]:
data = {
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Exam_Score":    [35, 40, 50, 55, 60, 65, 72, 78, 85, 90]
}

df = pd.DataFrame(data)

X = df[['Hours_Studied']]
y = df['Exam_Score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions) # This takes the absolute errors 
mse = mean_squared_error(y_test, predictions) # This squares the errors 
rmse = np.sqrt(mse) # This solve the problem with the mse
r2 = r2_score(y_test, predictions) # This deines the variation or correlation

print("MAE: ",mae)
print("MSE: ",mse)
print("RMSE: ", np.sqrt(mse))
print("R2: ",r2)

MAE:  1.6508620689655125
MSE:  3.115970570749097
RMSE:  1.7652111972081688
R2:  0.9938449964034586

## Logistics Regression

In [ ]:
# Logistics Regression

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

cancer = load_breast_cancer(as_frame=True)
df = cancer.frame

df.head(5)

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [ ]:
X = df.drop(columns=['target'])
y = df['target']

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=5000))
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

pipeline.fit(X_train, y_train)

predictions = pipeline.predict(X_test)

result_analysis = pd.DataFrame({
    'Actual': y_test,
    'Predicted': predictions
})

print('Accuracy Score: ', accuracy_score(y_test, predictions))
print('Precision Score: ', precision_score(y_test, predictions, average='macro'))
print('Recall Score: ', recall_score(y_test, predictions, average='macro'))
print('F1 Score: ', f1_score(y_test, predictions, average='macro'))

print('Confusion Matrix: \n', confusion_matrix(y_test, predictions))
print('Classification Report: \n', classification_report(y_test, predictions))

Accuracy Score:  0.9824561403508771
Precision Score:  0.9811507936507937
Recall Score:  0.9811507936507937
F1 Score:  0.9811507936507937
Confusion Matrix:
 [[41  1]
 [ 1 71]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

In [ ]:
# Logistics Regression
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

cancer = load_breast_cancer(as_frame=True)
df = cancer.frame

df.head(5)

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [ ]:
X = df.drop(columns=['target'])
y = df['target']

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=5000))
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

pipeline.fit(X_train, y_train)

predictions = pipeline.predict(X_test)

result_analysis = pd.DataFrame({
    'Actual': y_test,
    'Predicted': predictions
})

print('Accuracy Score: ', accuracy_score(y_test, predictions))
print('Precision Score: ', precision_score(y_test, predictions, average='macro'))
print('Recall Score: ', recall_score(y_test, predictions, average='macro'))
print('F1 Score: ', f1_score(y_test, predictions, average='macro'))

print('Confusion Matrix: \n', confusion_matrix(y_test, predictions))
print('Classification Report: \n', classification_report(y_test, predictions))

Accuracy Score:  0.9824561403508771
Precision Score:  0.9811507936507937
Recall Score:  0.9811507936507937
F1 Score:  0.9811507936507937
Confusion Matrix:
 [[41  1]
 [ 1 71]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

## Decision Tree Classifier

In [18]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, precision_score, f1_score, confusion_matrix, classification_report

cancer = load_breast_cancer(as_frame=True)
df = cancer.frame

df.head(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [19]:
X = df.drop(columns=['target'])
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = DecisionTreeClassifier(max_depth=5, min_samples_split=10, min_samples_leaf=2)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("Accuracy: ", accuracy_score(y_test, predictions))
print('Classification Report: \n', classification_report(y_test, predictions))

print('Train Acc: \n', model.score(X_train, y_train))
print('Test Acc: \n', model.score(X_test, y_test))

Accuracy:  0.8947368421052632
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.93      0.87        42
           1       0.95      0.88      0.91        72

    accuracy                           0.89       114
   macro avg       0.88      0.90      0.89       114
weighted avg       0.90      0.89      0.90       114

Train Acc:
 0.9824175824175824
Test Acc:
 0.8947368421052632