# Project: Employee Salary Analysis

In [2]:
# The below is the sample data o the employees in a company

import pandas as pd
import numpy as np

data = {
    "EmployeeID": [101,102,103,104,105,106,107,108,109,110,111,112],
    "Name": ["John","Alice","Bob","Emma","David","Sophia",
             "Mike","Olivia","James","Linda","Chris","Sarah"],
    "Age": [25,30,28,35,40,26,29,31,45,27,32,38],
    "Department": ["IT","HR","IT","Finance","Manager","HR",
                   "Finance","IT","Manager","HR","Finance","IT"],
    "Experience": [2,5,3,8,15,2,4,6,20,1,7,10],
    "Salary": [45000,55000,50000,70000,120000,48000,
               65000,60000,150000,42000,72000,80000]
}

df = pd.DataFrame(data)
print(df)

    EmployeeID    Name  Age Department  Experience  Salary
0          101    John   25         IT           2   45000
1          102   Alice   30         HR           5   55000
2          103     Bob   28         IT           3   50000
3          104    Emma   35    Finance           8   70000
4          105   David   40    Manager          15  120000
5          106  Sophia   26         HR           2   48000
6          107    Mike   29    Finance           4   65000
7          108  Olivia   31         IT           6   60000
8          109   James   45    Manager          20  150000
9          110   Linda   27         HR           1   42000
10         111   Chris   32    Finance           7   72000
11         112   Sarah   38         IT          10   80000

## Part 1: Data Explorations

In [10]:
# Task 1
print("First 5 rows:")
display(df.head(5))

print("Last 3 rows:")
display(df.tail(3))

print("Shape of the dataset:")
display(df.shape)

print("Columns:")
display(df.columns)

First 5 rows:

   EmployeeID   Name  Age Department  Experience  Salary
0         101   John   25         IT           2   45000
1         102  Alice   30         HR           5   55000
2         103    Bob   28         IT           3   50000
3         104   Emma   35    Finance           8   70000
4         105  David   40    Manager          15  120000

Last 3 rows:

    EmployeeID   Name  Age Department  Experience  Salary
9          110  Linda   27         HR           1   42000
10         111  Chris   32    Finance           7   72000
11         112  Sarah   38         IT          10   80000

Shape of the dataset:

(12, 6)

Columns:

Index(['EmployeeID', 'Name', 'Age', 'Department', 'Experience', 'Salary'], dtype='str')

In [11]:
# Task 2
print("Data Types:")
display(df.dtypes)

print("Statistics:")
display(df.describe())

print("Null Values:")
display(df.isna())

Data Types:

EmployeeID    int64
Name            str
Age           int64
Department      str
Experience    int64
Salary        int64
dtype: object

Statistics:

       EmployeeID        Age  Experience         Salary
count   12.000000  12.000000   12.000000      12.000000
mean   106.500000  32.166667    6.916667   71416.666667
std      3.605551   6.161956    5.712161   32505.826983
min    101.000000  25.000000    1.000000   42000.000000
25%    103.750000  27.750000    2.750000   49500.000000
50%    106.500000  30.500000    5.500000   62500.000000
75%    109.250000  35.750000    8.500000   74000.000000
max    112.000000  45.000000   20.000000  150000.000000

Null Values:

    EmployeeID   Name    Age  Department  Experience  Salary
0        False  False  False       False       False   False
1        False  False  False       False       False   False
2        False  False  False       False       False   False
3        False  False  False       False       False   False
4        False  False  False       False       False   False
5        False  False  False       False       False   False
6        False  False  False       False       False   False
7        False  False  False       False       False   False
8        False  False  False       False       False   False
9        False  False  False       False       False   False
10       False  False  False       False       False   False
11       False  False  False       False       False   False

In [18]:
# Task 3
print("Total Employees:")
display(df.shape[0])

print("Salary Stats:")
display(df['Salary'].agg(['mean', 'max', 'min']))

Total Employees:

12

Salary Stats:

mean     71416.666667
max     150000.000000
min      42000.000000
Name: Salary, dtype: float64

## Part 2: Selection & Filtering

In [24]:
# Task 4
print("All employees in IT Department:")
display(df[df['Department'].isin(['IT'])])

print("All employees in HR Department:")
display(df[df['Department'].isin(['HR'])])

All employees in IT Department:

    EmployeeID    Name  Age Department  Experience  Salary
0          101    John   25         IT           2   45000
2          103     Bob   28         IT           3   50000
7          108  Olivia   31         IT           6   60000
11         112   Sarah   38         IT          10   80000

All employees in HR Department:

   EmployeeID    Name  Age Department  Experience  Salary
1         102   Alice   30         HR           5   55000
5         106  Sophia   26         HR           2   48000
9         110   Linda   27         HR           1   42000

In [27]:
# Task 5
print("Emplyees Aged above 30:")
age_mask = df['Age'] > 30
display(df[age_mask])

print("Salary above 60000:")
salary_mask = df['Salary'] > 60000
display(df[salary_mask])

print("Experience greater than 5 years:")
experience_mask = df['Experience'] > 5
display(df[experience_mask])

Emplyees Aged above 30:

    EmployeeID    Name  Age Department  Experience  Salary
3          104    Emma   35    Finance           8   70000
4          105   David   40    Manager          15  120000
7          108  Olivia   31         IT           6   60000
8          109   James   45    Manager          20  150000
10         111   Chris   32    Finance           7   72000
11         112   Sarah   38         IT          10   80000

Salary above 60000:

    EmployeeID   Name  Age Department  Experience  Salary
3          104   Emma   35    Finance           8   70000
4          105  David   40    Manager          15  120000
6          107   Mike   29    Finance           4   65000
8          109  James   45    Manager          20  150000
10         111  Chris   32    Finance           7   72000
11         112  Sarah   38         IT          10   80000

Experience greater than 5 years:

    EmployeeID    Name  Age Department  Experience  Salary
3          104    Emma   35    Finance           8   70000
4          105   David   40    Manager          15  120000
7          108  Olivia   31         IT           6   60000
8          109   James   45    Manager          20  150000
10         111   Chris   32    Finance           7   72000
11         112   Sarah   38         IT          10   80000

In [28]:
# Task 6
print("Employees belonging to IT and Finance:")
display(df[df['Department'].isin(["IT", "Finance"])])

Employees belonging to IT and Finance:

    EmployeeID    Name  Age Department  Experience  Salary
0          101    John   25         IT           2   45000
2          103     Bob   28         IT           3   50000
3          104    Emma   35    Finance           8   70000
6          107    Mike   29    Finance           4   65000
7          108  Olivia   31         IT           6   60000
10         111   Chris   32    Finance           7   72000
11         112   Sarah   38         IT          10   80000

In [29]:
# Task 7
print("Salary greater then 70000:")
display(df.query("Salary > 70000"))

Salary greater then 70000:

    EmployeeID   Name  Age Department  Experience  Salary
4          105  David   40    Manager          15  120000
8          109  James   45    Manager          20  150000
10         111  Chris   32    Finance           7   72000
11         112  Sarah   38         IT          10   80000

## Part 3: Sorting

In [ ]:
# Task 8

## Part 4: Feature Engineering

In [30]:
# Task 10
print("create new bonus column:")
df['Bonus'] = df["Salary"] * 0.10
display(df)

create new bonus column:

    EmployeeID    Name  Age Department  Experience  Salary    Bonus
0          101    John   25         IT           2   45000   4500.0
1          102   Alice   30         HR           5   55000   5500.0
2          103     Bob   28         IT           3   50000   5000.0
3          104    Emma   35    Finance           8   70000   7000.0
4          105   David   40    Manager          15  120000  12000.0
5          106  Sophia   26         HR           2   48000   4800.0
6          107    Mike   29    Finance           4   65000   6500.0
7          108  Olivia   31         IT           6   60000   6000.0
8          109   James   45    Manager          20  150000  15000.0
9          110   Linda   27         HR           1   42000   4200.0
10         111   Chris   32    Finance           7   72000   7200.0
11         112   Sarah   38         IT          10   80000   8000.0

In [32]:
# Task 11
print("Create new column total pay:")
df['TotalPay'] = df['Salary'] + df['Bonus']
display(df)

Create new column total pay:

    EmployeeID    Name  Age Department  Experience  Salary    Bonus  TotalPay
0          101    John   25         IT           2   45000   4500.0   49500.0
1          102   Alice   30         HR           5   55000   5500.0   60500.0
2          103     Bob   28         IT           3   50000   5000.0   55000.0
3          104    Emma   35    Finance           8   70000   7000.0   77000.0
4          105   David   40    Manager          15  120000  12000.0  132000.0
5          106  Sophia   26         HR           2   48000   4800.0   52800.0
6          107    Mike   29    Finance           4   65000   6500.0   71500.0
7          108  Olivia   31         IT           6   60000   6000.0   66000.0
8          109   James   45    Manager          20  150000  15000.0  165000.0
9          110   Linda   27         HR           1   42000   4200.0   46200.0
10         111   Chris   32    Finance           7   72000   7200.0   79200.0
11         112   Sarah   38         IT          10   80000   8000.0   88000.0

In [34]:
# Task 12
df["Age_Group"] = df["Age"].map(
    lambda x: "Young" if x < 30 else "Mid" if x <= 40 else "Senior"
)
display(df)

,EmployeeID,Name,Age,Department,Experience,Salary,Bonus,TotalPay,Age_Group
0,101,John,25,IT,2,45000,4500.0,49500.0,Young
1,102,Alice,30,HR,5,55000,5500.0,60500.0,Mid
2,103,Bob,28,IT,3,50000,5000.0,55000.0,Young
3,104,Emma,35,Finance,8,70000,7000.0,77000.0,Mid
4,105,David,40,Manager,15,120000,12000.0,132000.0,Mid
5,106,Sophia,26,HR,2,48000,4800.0,52800.0,Young
6,107,Mike,29,Finance,4,65000,6500.0,71500.0,Young
7,108,Olivia,31,IT,6,60000,6000.0,66000.0,Mid
8,109,James,45,Manager,20,150000,15000.0,165000.0,Senior
9,110,Linda,27,HR,1,42000,4200.0,46200.0,Young
10,111,Chris,32,Finance,7,72000,7200.0,79200.0,Mid
11,112,Sarah,38,IT,10,80000,8000.0,88000.0,Mid

## Part 5: Aggregation

In [ ]:
# Task 14
print("Department wise employee count:")
display(df.groupby('Department').size())

Department wise employee count:

Department
Finance    3
HR         3
IT         4
Manager    2
dtype: int64

In [38]:
# Task 15
print("Total Salary paid by department:")
display(df.groupby('Department')['Salary'].sum())

Total Salary paid by department:

Department
Finance    207000
HR         145000
IT         235000
Manager    270000
Name: Salary, dtype: int64

In [41]:
# Task 16
print('Department with highest salary:')
display(df.groupby('Department')['Salary'].sum().idxmax())

Department with highest salary:

'Manager'